bodies:
- BODY mouth cup v2 no holes
joints: []
high resolution path: ..\3mm_mesh/high_res/
low resolution path: ..\3mm_mesh/low_res/
ignore inter-collision: true
gravity:
  x: 0.0
  y: 0.0
  z: 0.0
namespace: /ambf/env/
BODY mouth cup v2 no holes:
  name: mouth cup v2 no holes
  mesh: mouth cup v2 no holes.STL
  collision mesh type: CONVEX_HULL
  mass: 0.0
  inertia:
    ix: 0.0
    iy: 0.0
    iz: 0.0
  collision margin: 0.001
  scale: 1.0
  location:
    position:
      x: 0.1
      y: 0.0
      z: 0.5
    orientation:
      r: 1.0472
      p: -0.0
      y: -1.5708
  inertial offset:
    position:
      x: 0.0
      y: 0.0
      z: 0.0
    orientation:
      r: 0
      p: 0
      y: 0
  passive: false
  color: random
  publish children names: false
  publish joint names: false
  publish joint positions: false
  friction:
    rolling: 0.0
    static: 0.5
  restitution: 0.1
  damping:
    angular: 0.1
    linear: 0.04
  visible: true
  collision groups: []
